server:
  error:
    include-message: always
    include-binding-errors: always
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swp
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: true
    tracingEnabled: true
    corsEnabled: true
#  playground:
#    headers:
#      Authorization: Bearer TOKEN
#    tabs:
#      - name: Bank account sample query
#        query: classpath:playground/bank_account.graphql
#        variables: classpath:playground/bank_account_variables.json

voyager:
  enabled: true